---
# add EPEL/Remi repositories
- name: add repositories
  yum: name={{item}}
  with_items:
    - http://ftp.riken.jp/Linux/fedora/epel/6/x86_64/epel-release-6-8.noarch.rpm
    - http://rpms.famillecollet.com/enterprise/remi-release-6.rpm

# yum -y update
- name: upgrade all packages
  yum: name=* state=latest

# for diasble selinux
- name: selinux python install
  yum: name=libselinux-python state=installed

# disable unnecessary services
- name: iptables disable
  service: name=iptables state=stopped enabled=False
  
- name: ip6tables disable
  service: name=ip6tables state=stopped enabled=False
  
- name: postfix disable
  service: name=postfix state=stopped enabled=False

- name: selinux disable
  selinux: state=disabled

