---
- name: copy mongodb-org repos
  copy: src=mongodb-org-3.0.repo dest=/etc/yum.repos.d/mongodb-org-3.0.repo

- name: install mongod
  yum: name=mongodb-org state=latest
  notify: restart mongod

- name: be sure mongod is running and enabled
  service: name=mongod state=started enabled=yes 

